# 数据操作 & 数据预处理

## 一、数据操作

### 1. 张量 tensor

导入 `torch`

In [4]:
import torch

创建张量 `tensor`，张量就是数组

In [9]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

访问张量的形状和其中元素的数量

In [10]:
x.shape

torch.Size([12])

In [12]:
x.numel()

12

改变张量的形状

In [14]:
x = x.reshape(-1, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

创建张量的 api ：

In [15]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.ones((3, 4, 5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

也可以直接调用 `tensor` 的构造函数，创建指定的张量：

In [42]:
torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### 2. 张量的元素级运算

标准算数运算符都是按元素运算：

In [10]:
x = torch.ones(1, 4)
y = torch.arange(1,5, dtype=torch.float32)
x + y, x - y, x * y, x / y, x ** y

(tensor([[2., 3., 4., 5.]]),
 tensor([[ 0., -1., -2., -3.]]),
 tensor([[1., 2., 3., 4.]]),
 tensor([[1.0000, 0.5000, 0.3333, 0.2500]]),
 tensor([[1., 1., 1., 1.]]))

按元素指数运算：

In [11]:
torch.exp(x)

tensor([[2.7183, 2.7183, 2.7183, 2.7183]])

按元素判断逻辑：

In [12]:
x == y

tensor([[ True, False, False, False]])

张量按元素求和：

In [13]:
x.sum()

tensor(4.)

In [22]:
A = torch.arange(20 * 2, dtype=float).reshape(2, 5, 4)
A, A.sum(), A.sum(axis=0), A.sum(axis=1), A.mean(axis=0)  # 加入 axis 参数表示按维度求和属于有维度的运算

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]], dtype=torch.float64),
 tensor(780., dtype=torch.float64),
 tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]], dtype=torch.float64),
 tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]], dtype=torch.float64),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]], dtype=torch.float64))

广播机制：

In [24]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [25]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

广播机制需要维度相同（都是2维或者3维等等），以下就不能成立：

In [39]:
a = torch.arange(6).reshape(3, 2)
b = a.sum(axis=1)
c = a.sum(axis=1, keepdims=True)
try:
    a + b
except:
    print("因为降维导致无法广播")
a.shape, b.shape, c.shape, a + c

因为降维导致无法广播


(torch.Size([3, 2]),
 torch.Size([3]),
 torch.Size([3, 1]),
 tensor([[ 1,  2],
         [ 7,  8],
         [13, 14]]))

这种求和、求均值等等类似操作要注意是否会被降维。

累加求和（不会降维）：

In [45]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
X.cumsum(axis = 1), X.shape, X.cumsum(axis = 0).shape

(tensor([[ 1,  3,  6],
         [ 4,  9, 15]]),
 torch.Size([2, 3]),
 torch.Size([2, 3]))

### 3. 张量的向量级运算

张量合并：

In [52]:
X = torch.arange(12, dtype=float).reshape(3, 4)
Y = torch.rand(3, 4, dtype=float)
# 在第 0 维拼接，在第 1 维拼接
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [ 0.7961,  0.3387,  0.2781,  0.9865],
         [ 0.5832,  0.6856,  0.0233,  0.3938],
         [ 0.4723,  0.9297,  0.6180,  0.8659]], dtype=torch.float64),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  0.7961,  0.3387,  0.2781,  0.9865],
         [ 4.0000,  5.0000,  6.0000,  7.0000,  0.5832,  0.6856,  0.0233,  0.3938],
         [ 8.0000,  9.0000, 10.0000, 11.0000,  0.4723,  0.9297,  0.6180,  0.8659]],
        dtype=torch.float64))

向量/矩阵点积：

In [54]:
torch.mm(X, Y.T)
# 向量 * 向量：torch.dot()
# 矩阵 * 向量：torch.mv()

tensor([[ 3.8545,  1.9136,  4.7635],
        [13.4524,  8.6571, 16.3075],
        [23.0503, 15.4007, 27.8514]], dtype=torch.float64)

范数：

In [58]:
u = torch.arange(4, dtype=float)
m = torch.arange(4, dtype=float).reshape(2, 2)
torch.norm(u), torch.norm(m), torch.abs(u).sum()  # 2 范数， 2 范数， 1 范数

(tensor(3.7417, dtype=torch.float64),
 tensor(3.7417, dtype=torch.float64),
 tensor(6., dtype=torch.float64))

### 4. tensor 和 nupmy 转换

In [6]:
A = X.numpy()
B = torch.tensor(A)
A, B

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int64),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

也可以把标量转换为 int 型：

In [7]:
a = torch.tensor([3.])
a, a.item(), float(a), int(a)

(tensor([3.]), 3.0, 3.0, 3)

矩阵转置：

In [8]:
B.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

## 二、数据预处理

创建人工数据集，存储于 csv （逗号分隔符）文件

In [53]:
import os

os.makedirs(os.path.join('../', 'data'), exist_ok=True)
data_file = os.path.join('../', 'data/', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, Prise\n')
    f.write('NA, Pave, 127500\n')
    f.write('2, NA, 106000\n')
    f.write('4, NA, 178100\n')
    f.write('NA, NA, 140000\n')

从创建的 csv 文件中加载原始数据集

In [55]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms  Alley   Prise
0       NaN   Pave  127500
1       2.0     NA  106000
2       4.0     NA  178100
3       NaN     NA  140000

对于数值类型的缺失数据，如果不想删除，可以使用插值进行填充：

In [65]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
inputs

NumRooms  Alley
0       3.0   Pave
1       2.0     NA
2       4.0     NA
3       3.0     NA

对于离散值或者类别，用独热编码：

In [66]:
inputs = pd.get_dummies(inputs, dummy_na=True, dtype=int)
inputs

NumRooms   Alley_ NA   Alley_ Pave   Alley_nan
0       3.0           0             1           0
1       2.0           1             0           0
2       4.0           1             0           0
3       3.0           1             0           0

全都转为数值类型后，转为张量格式：

In [67]:
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 0., 1., 0.],
         [2., 1., 0., 0.],
         [4., 1., 0., 0.],
         [3., 1., 0., 0.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))